### PR TITLE
Add AUD as WebPusher option (#63)

### PR DESCRIPTION
**Pull request by mwent-cray**
Had to mention #63

### CODE REVIEW

**Comment by jrconlin** [comment]
I'm a bit confused why you need this.

I already [pull the `aud`](https://github.com/web-push-libs/pywebpush/blob/master/pywebpush/__init__.py#L338) from the endpoint for VAPID (if the `aud` isn't already declared in the VAPID info. You also don't appear to be doing anything with the `aud` once you extract it. 

Can you help me understand the goal of this issue and PR?

**Comment by mwent-cray** [comment]
The reason is, that in the backend I am constructing the vapid headers manually because I want/need to reuse WebPusher

whereas webpush is a use-once class.

By moving the aud to the WebPusher class it will become easier to handle outside of the webpush class

**Comment by jrconlin** [comment]
Still a bit confused. You don't have to use pywebpush's VAPID. You can just pass in the header via the same thing I'm doing in the convenience function.
```
result = WebPusher(subscription_info).send(
        data,
        vapid_headers,
        content_encoding=content_encoding
)
```
Heck, you could cache the `WebPush()` object if you wanted and then just call the `.send()` method. 
Or call `.encode()` if you want to batch up your deliveries for later. 

The `vapid_headers` are just a dict of the `Authorization` header and the `Crypto-Key` (if you're using the older VAPID 'webpush' format.)

I can kinda see where pulling the aud makes sense for VAPID, but considering that VAPID is supposed to be "voluntary", I'm not sure that it's really pywebpush's problem. (Yes, I know that Google makes VAPID a good deal less Voluntary than the spec writers would prefer.)

**Comment by jrconlin** [comment]
Tell you what, this is a minor change and if it's useful for you, I'll put aside my concerns. 

If you can, though, can you add a check to `test_init` so that someone doesn't break your code with a change in the future? Then 👍

**Comment by mwent-cray** [comment]
The thing is, you cannot cache the current webpush as this object returns a results from send.

By moving aud into WebPusher you can cache the WebPush object and reuse the aud (since it is set only once per WebPusher object anyway) without the need to re-generate this variable (optimization)

vapid is kinda necessary for google and from what I've read will become standard when running over SSL

**Comment by jrconlin** [comment]
Pretty sure Vapid will always be voluntary. Kinda part of the name. ;)

I'm also pretty sure that every Push Server will be over https, so that's already being handled. 

Thanks!

**Pull request merged**
