### PR TITLE
use cryptography==1.8.2

### PR DESCRIPTION
**Pull request by perosb**
1.8.2:
Fixed a compilation bug affecting OpenSSL 1.1.0f

### CODE REVIEW

**Comment by safwanrahman** [comment]
Can you try updating it to 1.9?

**Comment by safwanrahman** [comment]
@jrconlin Can have a review in the changelog?

**Comment by perosb** [comment]
Requires https://github.com/web-push-libs/vapid/pull/51

**Comment by perosb** [comment]
I had to downgrade form 1.9 to 1.8.2 due to vapid tests fails on 1.9.

**Comment by perosb** [comment]
not sure how you manage the dependencies but pywebpush/travis won't build until vapid is 1.2.4 with same cryptography version.

**Comment by jrconlin** [comment]
Published to pypi. Thanks!

**Pull request merged**
